# Generated by Django 5.0.4 on 2024-05-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
